openapi: 3.0.3
info:
  title: swaan
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/provider/login:
    post:
      summary: ''
      operationId: postApiProviderLogin
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Provider Auth'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: toy.keaton@example.org
                password:
                  type: string
                  description: ''
                  example: quis
                device_id:
                  type: string
                  description: ''
                  example: sapiente
              required:
                - email
                - password
                - device_id
      security: []
  /api/provider/register:
    post:
      summary: ''
      operationId: postApiProviderRegister
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: multipart/form-data
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Provider Auth'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: repellat
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: bernita66@example.org
                phone:
                  type: string
                  description: ''
                  example: quia
                password:
                  type: string
                  description: ''
                  example: sint
                device_id:
                  type: string
                  description: ''
                  example: qui
                image:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 1024 kilobytes.'
              required:
                - name
                - email
                - phone
                - password
                - device_id
                - image
      security: []
  /api/provider:
    get:
      summary: ''
      operationId: getApiProvider
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Provider Basic'
  /api/provider/services:
    get:
      summary: ''
      operationId: getApiProviderServices
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Provider Service'
    post:
      summary: ''
      operationId: postApiProviderServices
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: multipart/form-data
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Provider Service'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: atque
                category_id:
                  type: integer
                  description: ''
                  example: 5
                sub_category_id:
                  type: integer
                  description: ''
                  example: 18
                description:
                  type: string
                  description: 'Must not be greater than 5000 characters.'
                  example: 'Impedit sequi maxime illum praesentium quisquam et.'
                latitude:
                  type: string
                  description: ''
                  example: doloremque
                longitude:
                  type: string
                  description: ''
                  example: odio
                type:
                  type: string
                  description: 'Must be one of <code>fixed</code> or <code>hourly</code>.'
                  example: fixed
                price:
                  type: number
                  description: ''
                  example: 69009073.474145
                discount:
                  type: number
                  description: ''
                  example: 5359.46
                hours:
                  type: integer
                  description: 'This field is required when <code>minutes</code> is not present.'
                  example: 8
                minutes:
                  type: integer
                  description: 'This field is required when <code>hours</code> is not present.'
                  example: 20
                images:
                  type: array
                  description: 'Must be an image. Must not be greater than 1024 kilobytes.'
                  items:
                    type: string
                    format: binary
                slots:
                  type: array
                  description: ''
                  example:
                    - quae
                  items:
                    type: integer
              required:
                - name
                - category_id
                - type
                - price
  /api/provider/slots:
    get:
      summary: ''
      operationId: getApiProviderSlots
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Provider Slot'
    post:
      summary: ''
      operationId: postApiProviderSlots
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Provider Slot'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                day:
                  type: string
                  description: ''
                  example: est
                start_time:
                  type: string
                  description: ''
                  example: voluptatem
                end_time:
                  type: string
                  description: ''
                  example: dicta
              required:
                - day
                - start_time
                - end_time
  '/api/provider/slots/{slot}':
    delete:
      summary: ''
      operationId: deleteApiProviderSlotsSlot
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Provider Slot'
    parameters:
      -
        in: path
        name: slot
        description: 'The slot.'
        example: consectetur
        required: true
        schema:
          type: string
  /api/user/login:
    post:
      summary: 'Login (Firebase based)'
      operationId: loginFirebaseBased
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User Auth'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: sit
                device_id:
                  type: string
                  description: 'Must be 36 characters.'
                  example: vrqzkyrfdcphmpojboqhmmojtorsnifqzczr
              required:
                - token
                - device_id
      security: []
  /api/user/old-login:
    post:
      summary: 'Old Login (will be removed)'
      operationId: oldLoginwillBeRemoved
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User Auth'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: collins.juanita@example.com
                password:
                  type: string
                  description: ''
                  example: sint
                device_id:
                  type: string
                  description: ''
                  example: eos
              required:
                - email
                - password
                - device_id
      security: []
  /api/user/register:
    post:
      summary: 'Register (will be removed)'
      operationId: registerwillBeRemoved
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User Auth'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: rem
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: davion16@example.org
                phone:
                  type: string
                  description: ''
                  example: veritatis
                password:
                  type: string
                  description: ''
                  example: sit
                device_id:
                  type: string
                  description: ''
                  example: illum
              required:
                - name
                - email
                - phone
                - password
                - device_id
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'User Basic'
  /api/user/categories:
    get:
      summary: ''
      operationId: getApiUserCategories
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'User Basic'
  /api/user/services:
    get:
      summary: ''
      operationId: getApiUserServices
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'User Basic'
tags:
  -
    name: 'Provider Auth'
    description: "\nAPIs for provider authentication and registration"
  -
    name: 'Provider Basic'
    description: "\nAPIs for provider basic operations"
  -
    name: 'Provider Service'
    description: "\nAPIs for provider service operations"
  -
    name: 'Provider Slot'
    description: "\nAPIs for provider slot operations"
  -
    name: 'User Auth'
    description: "\nAPIs for user authentication and registration"
  -
    name: 'User Basic'
    description: "\nAPIs for user basic operations"
